// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module soft_max (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dense_array_address0,
        dense_array_ce0,
        dense_array_q0,
        pred_V_V_TDATA,
        pred_V_V_TVALID,
        pred_V_V_TREADY
);

parameter    ap_ST_fsm_state1 = 36'd1;
parameter    ap_ST_fsm_state2 = 36'd2;
parameter    ap_ST_fsm_state3 = 36'd4;
parameter    ap_ST_fsm_state4 = 36'd8;
parameter    ap_ST_fsm_state5 = 36'd16;
parameter    ap_ST_fsm_state6 = 36'd32;
parameter    ap_ST_fsm_state7 = 36'd64;
parameter    ap_ST_fsm_state8 = 36'd128;
parameter    ap_ST_fsm_state9 = 36'd256;
parameter    ap_ST_fsm_state10 = 36'd512;
parameter    ap_ST_fsm_state11 = 36'd1024;
parameter    ap_ST_fsm_state12 = 36'd2048;
parameter    ap_ST_fsm_state13 = 36'd4096;
parameter    ap_ST_fsm_state14 = 36'd8192;
parameter    ap_ST_fsm_state15 = 36'd16384;
parameter    ap_ST_fsm_state16 = 36'd32768;
parameter    ap_ST_fsm_state17 = 36'd65536;
parameter    ap_ST_fsm_state18 = 36'd131072;
parameter    ap_ST_fsm_state19 = 36'd262144;
parameter    ap_ST_fsm_state20 = 36'd524288;
parameter    ap_ST_fsm_state21 = 36'd1048576;
parameter    ap_ST_fsm_state22 = 36'd2097152;
parameter    ap_ST_fsm_state23 = 36'd4194304;
parameter    ap_ST_fsm_state24 = 36'd8388608;
parameter    ap_ST_fsm_state25 = 36'd16777216;
parameter    ap_ST_fsm_state26 = 36'd33554432;
parameter    ap_ST_fsm_state27 = 36'd67108864;
parameter    ap_ST_fsm_state28 = 36'd134217728;
parameter    ap_ST_fsm_state29 = 36'd268435456;
parameter    ap_ST_fsm_state30 = 36'd536870912;
parameter    ap_ST_fsm_state31 = 36'd1073741824;
parameter    ap_ST_fsm_state32 = 36'd2147483648;
parameter    ap_ST_fsm_state33 = 36'd4294967296;
parameter    ap_ST_fsm_state34 = 36'd8589934592;
parameter    ap_ST_fsm_state35 = 36'd17179869184;
parameter    ap_ST_fsm_state36 = 36'd34359738368;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] dense_array_address0;
output   dense_array_ce0;
input  [31:0] dense_array_q0;
output  [15:0] pred_V_V_TDATA;
output   pred_V_V_TVALID;
input   pred_V_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] dense_array_address0;
reg dense_array_ce0;
reg pred_V_V_TVALID;

(* fsm_encoding = "none" *) reg   [35:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    pred_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state16;
wire   [31:0] grp_fu_143_p2;
reg   [31:0] reg_154;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state23;
wire   [3:0] i_fu_166_p2;
reg   [3:0] i_reg_477;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln15_fu_160_p2;
wire   [31:0] grp_fu_130_p2;
wire    ap_CS_fsm_state14;
wire   [3:0] j_fu_183_p2;
reg   [3:0] j_reg_495;
wire    ap_CS_fsm_state15;
wire   [0:0] icmp_ln20_fu_177_p2;
wire   [31:0] grp_fu_135_p2;
reg   [31:0] v_assign_reg_505;
wire    ap_CS_fsm_state33;
reg   [0:0] p_Result_s_reg_511;
wire    ap_CS_fsm_state35;
wire   [51:0] trunc_ln565_fu_224_p1;
reg   [51:0] trunc_ln565_reg_516;
wire   [0:0] icmp_ln571_fu_228_p2;
reg   [0:0] icmp_ln571_reg_521;
wire   [11:0] F2_fu_234_p2;
reg   [11:0] F2_reg_527;
reg   [31:0] sum_0_reg_96;
reg   [3:0] i_0_reg_108;
reg   [3:0] j_0_reg_119;
wire   [63:0] zext_ln17_fu_172_p1;
wire   [63:0] zext_ln22_fu_189_p1;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state34;
wire   [63:0] grp_fu_140_p1;
wire   [63:0] ireg_V_fu_194_p1;
wire   [10:0] exp_tmp_V_fu_210_p4;
wire   [62:0] trunc_ln556_fu_198_p1;
wire   [11:0] zext_ln461_fu_220_p1;
wire   [52:0] tmp_1_fu_240_p3;
wire   [53:0] p_Result_1_fu_247_p1;
wire   [53:0] man_V_1_fu_251_p2;
wire   [0:0] icmp_ln581_fu_264_p2;
wire   [11:0] add_ln581_fu_269_p2;
wire   [11:0] sub_ln581_fu_274_p2;
wire  signed [11:0] sh_amt_fu_279_p3;
wire   [53:0] man_V_2_fu_257_p3;
wire  signed [31:0] sext_ln581_fu_287_p1;
wire   [53:0] zext_ln586_fu_312_p1;
wire   [53:0] ashr_ln586_fu_316_p2;
wire   [31:0] bitcast_ln696_fu_326_p1;
wire   [0:0] tmp_4_fu_329_p3;
wire   [14:0] trunc_ln583_fu_296_p1;
wire   [14:0] sext_ln581cast_fu_345_p1;
wire   [0:0] icmp_ln582_fu_291_p2;
wire   [0:0] xor_ln571_fu_355_p2;
wire   [0:0] or_ln582_fu_366_p2;
wire   [0:0] xor_ln582_fu_371_p2;
wire   [0:0] icmp_ln585_fu_300_p2;
wire   [0:0] and_ln581_fu_377_p2;
wire   [0:0] xor_ln585_fu_383_p2;
wire   [0:0] or_ln581_fu_401_p2;
wire   [0:0] icmp_ln603_fu_306_p2;
wire   [0:0] xor_ln581_fu_407_p2;
wire   [0:0] and_ln603_fu_413_p2;
wire   [14:0] shl_ln604_fu_349_p2;
wire   [14:0] trunc_ln586_fu_322_p1;
wire   [0:0] and_ln585_1_fu_395_p2;
wire   [0:0] and_ln585_fu_389_p2;
wire   [14:0] select_ln588_fu_337_p3;
wire   [0:0] and_ln582_fu_360_p2;
wire   [0:0] or_ln603_fu_427_p2;
wire   [14:0] select_ln603_fu_419_p3;
wire   [14:0] select_ln603_1_fu_433_p3;
wire   [0:0] or_ln603_1_fu_441_p2;
wire   [0:0] or_ln603_2_fu_455_p2;
wire   [14:0] select_ln603_2_fu_447_p3;
wire   [14:0] tmp_V_fu_461_p3;
reg   [35:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 36'd1;
end

cnn_fadd_32ns_32nbkb #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
cnn_fadd_32ns_32nbkb_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_0_reg_96),
    .din1(reg_154),
    .ce(1'b1),
    .dout(grp_fu_130_p2)
);

cnn_fdiv_32ns_32ncud #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
cnn_fdiv_32ns_32ncud_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_154),
    .din1(sum_0_reg_96),
    .ce(1'b1),
    .dout(grp_fu_135_p2)
);

cnn_fpext_32ns_64dEe #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
cnn_fpext_32ns_64dEe_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v_assign_reg_505),
    .ce(1'b1),
    .dout(grp_fu_140_p1)
);

cnn_fexp_32ns_32neOg #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
cnn_fexp_32ns_32neOg_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(dense_array_q0),
    .ce(1'b1),
    .dout(grp_fu_143_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        i_0_reg_108 <= i_reg_477;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_108 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln15_fu_160_p2 == 1'd1))) begin
        j_0_reg_119 <= 4'd0;
    end else if (((pred_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
        j_0_reg_119 <= j_reg_495;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        sum_0_reg_96 <= grp_fu_130_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        sum_0_reg_96 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        F2_reg_527 <= F2_fu_234_p2;
        icmp_ln571_reg_521 <= icmp_ln571_fu_228_p2;
        p_Result_s_reg_511 <= ireg_V_fu_194_p1[32'd63];
        trunc_ln565_reg_516 <= trunc_ln565_fu_224_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_477 <= i_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        j_reg_495 <= j_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state10))) begin
        reg_154 <= grp_fu_143_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        v_assign_reg_505 <= grp_fu_135_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state15) & (icmp_ln20_fu_177_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln20_fu_177_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dense_array_address0 = zext_ln22_fu_189_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_array_address0 = zext_ln17_fu_172_p1;
    end else begin
        dense_array_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state2))) begin
        dense_array_ce0 = 1'b1;
    end else begin
        dense_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        pred_V_V_TDATA_blk_n = pred_V_V_TREADY;
    end else begin
        pred_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((pred_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
        pred_V_V_TVALID = 1'b1;
    end else begin
        pred_V_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln15_fu_160_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (icmp_ln20_fu_177_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            if (((pred_V_V_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state36))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_fu_234_p2 = (12'd1075 - zext_ln461_fu_220_p1);

assign add_ln581_fu_269_p2 = ($signed(12'd4087) + $signed(F2_reg_527));

assign and_ln581_fu_377_p2 = (xor_ln582_fu_371_p2 & icmp_ln581_fu_264_p2);

assign and_ln582_fu_360_p2 = (xor_ln571_fu_355_p2 & icmp_ln582_fu_291_p2);

assign and_ln585_1_fu_395_p2 = (icmp_ln585_fu_300_p2 & and_ln581_fu_377_p2);

assign and_ln585_fu_389_p2 = (xor_ln585_fu_383_p2 & and_ln581_fu_377_p2);

assign and_ln603_fu_413_p2 = (xor_ln581_fu_407_p2 & icmp_ln603_fu_306_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ashr_ln586_fu_316_p2 = $signed(man_V_2_fu_257_p3) >>> zext_ln586_fu_312_p1;

assign bitcast_ln696_fu_326_p1 = v_assign_reg_505;

assign exp_tmp_V_fu_210_p4 = {{ireg_V_fu_194_p1[62:52]}};

assign i_fu_166_p2 = (i_0_reg_108 + 4'd1);

assign icmp_ln15_fu_160_p2 = ((i_0_reg_108 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_177_p2 = ((j_0_reg_119 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln571_fu_228_p2 = ((trunc_ln556_fu_198_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln581_fu_264_p2 = (($signed(F2_reg_527) > $signed(12'd9)) ? 1'b1 : 1'b0);

assign icmp_ln582_fu_291_p2 = ((F2_reg_527 == 12'd9) ? 1'b1 : 1'b0);

assign icmp_ln585_fu_300_p2 = ((sh_amt_fu_279_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln603_fu_306_p2 = ((sh_amt_fu_279_p3 < 12'd15) ? 1'b1 : 1'b0);

assign ireg_V_fu_194_p1 = grp_fu_140_p1;

assign j_fu_183_p2 = (j_0_reg_119 + 4'd1);

assign man_V_1_fu_251_p2 = (54'd0 - p_Result_1_fu_247_p1);

assign man_V_2_fu_257_p3 = ((p_Result_s_reg_511[0:0] === 1'b1) ? man_V_1_fu_251_p2 : p_Result_1_fu_247_p1);

assign or_ln581_fu_401_p2 = (or_ln582_fu_366_p2 | icmp_ln581_fu_264_p2);

assign or_ln582_fu_366_p2 = (icmp_ln582_fu_291_p2 | icmp_ln571_reg_521);

assign or_ln603_1_fu_441_p2 = (and_ln585_fu_389_p2 | and_ln582_fu_360_p2);

assign or_ln603_2_fu_455_p2 = (or_ln603_fu_427_p2 | or_ln603_1_fu_441_p2);

assign or_ln603_fu_427_p2 = (and_ln603_fu_413_p2 | and_ln585_1_fu_395_p2);

assign p_Result_1_fu_247_p1 = tmp_1_fu_240_p3;

assign pred_V_V_TDATA = $signed(tmp_V_fu_461_p3);

assign select_ln588_fu_337_p3 = ((tmp_4_fu_329_p3[0:0] === 1'b1) ? 15'd32767 : 15'd0);

assign select_ln603_1_fu_433_p3 = ((and_ln585_fu_389_p2[0:0] === 1'b1) ? select_ln588_fu_337_p3 : trunc_ln583_fu_296_p1);

assign select_ln603_2_fu_447_p3 = ((or_ln603_fu_427_p2[0:0] === 1'b1) ? select_ln603_fu_419_p3 : select_ln603_1_fu_433_p3);

assign select_ln603_fu_419_p3 = ((and_ln603_fu_413_p2[0:0] === 1'b1) ? shl_ln604_fu_349_p2 : trunc_ln586_fu_322_p1);

assign sext_ln581_fu_287_p1 = sh_amt_fu_279_p3;

assign sext_ln581cast_fu_345_p1 = sext_ln581_fu_287_p1[14:0];

assign sh_amt_fu_279_p3 = ((icmp_ln581_fu_264_p2[0:0] === 1'b1) ? add_ln581_fu_269_p2 : sub_ln581_fu_274_p2);

assign shl_ln604_fu_349_p2 = trunc_ln583_fu_296_p1 << sext_ln581cast_fu_345_p1;

assign sub_ln581_fu_274_p2 = (12'd9 - F2_reg_527);

assign tmp_1_fu_240_p3 = {{1'd1}, {trunc_ln565_reg_516}};

assign tmp_4_fu_329_p3 = bitcast_ln696_fu_326_p1[32'd31];

assign tmp_V_fu_461_p3 = ((or_ln603_2_fu_455_p2[0:0] === 1'b1) ? select_ln603_2_fu_447_p3 : 15'd0);

assign trunc_ln556_fu_198_p1 = ireg_V_fu_194_p1[62:0];

assign trunc_ln565_fu_224_p1 = ireg_V_fu_194_p1[51:0];

assign trunc_ln583_fu_296_p1 = man_V_2_fu_257_p3[14:0];

assign trunc_ln586_fu_322_p1 = ashr_ln586_fu_316_p2[14:0];

assign xor_ln571_fu_355_p2 = (icmp_ln571_reg_521 ^ 1'd1);

assign xor_ln581_fu_407_p2 = (or_ln581_fu_401_p2 ^ 1'd1);

assign xor_ln582_fu_371_p2 = (or_ln582_fu_366_p2 ^ 1'd1);

assign xor_ln585_fu_383_p2 = (icmp_ln585_fu_300_p2 ^ 1'd1);

assign zext_ln17_fu_172_p1 = i_0_reg_108;

assign zext_ln22_fu_189_p1 = j_0_reg_119;

assign zext_ln461_fu_220_p1 = exp_tmp_V_fu_210_p4;

assign zext_ln586_fu_312_p1 = $unsigned(sext_ln581_fu_287_p1);

endmodule //soft_max
