// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_layer.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_layer::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_layer::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<21> dense_layer::ap_ST_fsm_state1 = "1";
const sc_lv<21> dense_layer::ap_ST_fsm_state2 = "10";
const sc_lv<21> dense_layer::ap_ST_fsm_state3 = "100";
const sc_lv<21> dense_layer::ap_ST_fsm_state4 = "1000";
const sc_lv<21> dense_layer::ap_ST_fsm_state5 = "10000";
const sc_lv<21> dense_layer::ap_ST_fsm_state6 = "100000";
const sc_lv<21> dense_layer::ap_ST_fsm_state7 = "1000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state8 = "10000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state9 = "100000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state10 = "1000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state11 = "10000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state12 = "100000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<21> dense_layer::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<32> dense_layer::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dense_layer::ap_const_lv32_1 = "1";
const sc_lv<32> dense_layer::ap_const_lv32_2 = "10";
const sc_lv<1> dense_layer::ap_const_lv1_0 = "0";
const sc_lv<32> dense_layer::ap_const_lv32_3 = "11";
const sc_lv<1> dense_layer::ap_const_lv1_1 = "1";
const sc_lv<32> dense_layer::ap_const_lv32_4 = "100";
const sc_lv<32> dense_layer::ap_const_lv32_5 = "101";
const sc_lv<32> dense_layer::ap_const_lv32_6 = "110";
const sc_lv<32> dense_layer::ap_const_lv32_7 = "111";
const sc_lv<32> dense_layer::ap_const_lv32_B = "1011";
const sc_lv<32> dense_layer::ap_const_lv32_C = "1100";
const sc_lv<32> dense_layer::ap_const_lv32_D = "1101";
const sc_lv<32> dense_layer::ap_const_lv32_E = "1110";
const sc_lv<32> dense_layer::ap_const_lv32_F = "1111";
const sc_lv<32> dense_layer::ap_const_lv32_12 = "10010";
const sc_lv<4> dense_layer::ap_const_lv4_0 = "0000";
const sc_lv<32> dense_layer::ap_const_lv32_13 = "10011";
const sc_lv<8> dense_layer::ap_const_lv8_0 = "00000000";
const sc_lv<32> dense_layer::ap_const_lv32_14 = "10100";
const sc_lv<32> dense_layer::ap_const_lv32_8 = "1000";
const sc_lv<4> dense_layer::ap_const_lv4_1 = "1";
const sc_lv<4> dense_layer::ap_const_lv4_9 = "1001";
const sc_lv<4> dense_layer::ap_const_lv4_A = "1010";
const sc_lv<8> dense_layer::ap_const_lv8_A0 = "10100000";
const sc_lv<8> dense_layer::ap_const_lv8_1 = "1";
const sc_lv<3> dense_layer::ap_const_lv3_0 = "000";
const sc_lv<10> dense_layer::ap_const_lv10_2CC = "1011001100";
const sc_lv<32> dense_layer::ap_const_lv32_18 = "11000";
const sc_lv<25> dense_layer::ap_const_lv25_0 = "0000000000000000000000000";
const sc_lv<32> dense_layer::ap_const_lv32_1D = "11101";
const sc_lv<2> dense_layer::ap_const_lv2_3 = "11";
const sc_lv<32> dense_layer::ap_const_lv32_1E = "11110";
const sc_lv<32> dense_layer::ap_const_lv32_FFFFFFE8 = "11111111111111111111111111101000";
const sc_lv<32> dense_layer::ap_const_lv32_1F = "11111";
const sc_lv<31> dense_layer::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<5> dense_layer::ap_const_lv5_17 = "10111";
const sc_lv<30> dense_layer::ap_const_lv30_3FFFFFFF = "111111111111111111111111111111";
const sc_lv<30> dense_layer::ap_const_lv30_0 = "000000000000000000000000000000";
const sc_lv<30> dense_layer::ap_const_lv30_3FFFFFE8 = "111111111111111111111111101000";
const sc_lv<32> dense_layer::ap_const_lv32_FFFFFFE7 = "11111111111111111111111111100111";
const sc_lv<32> dense_layer::ap_const_lv32_19 = "11001";
const sc_lv<8> dense_layer::ap_const_lv8_7F = "1111111";
const sc_lv<8> dense_layer::ap_const_lv8_7E = "1111110";
const sc_lv<8> dense_layer::ap_const_lv8_C = "1100";
const sc_lv<32> dense_layer::ap_const_lv32_17 = "10111";
const sc_lv<9> dense_layer::ap_const_lv9_0 = "000000000";
const sc_lv<17> dense_layer::ap_const_lv17_1FFFF = "11111111111111111";
const sc_lv<4> dense_layer::ap_const_lv4_8 = "1000";
const sc_lv<15> dense_layer::ap_const_lv15_7FFF = "111111111111111";
const sc_lv<15> dense_layer::ap_const_lv15_0 = "000000000000000";
const sc_lv<15> dense_layer::ap_const_lv15_7FE8 = "111111111101000";
const sc_lv<8> dense_layer::ap_const_lv8_6 = "110";
const bool dense_layer::ap_const_boolean_1 = true;

dense_layer::dense_layer(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dense_weights_V_U = new dense_layer_densefYi("dense_weights_V_U");
    dense_weights_V_U->clk(ap_clk);
    dense_weights_V_U->reset(ap_rst);
    dense_weights_V_U->address0(dense_weights_V_address0);
    dense_weights_V_U->ce0(dense_weights_V_ce0);
    dense_weights_V_U->q0(dense_weights_V_q0);
    dense_biases_V_U = new dense_layer_denseg8j("dense_biases_V_U");
    dense_biases_V_U->clk(ap_clk);
    dense_biases_V_U->reset(ap_rst);
    dense_biases_V_U->address0(dense_biases_V_address0);
    dense_biases_V_U->ce0(dense_biases_V_ce0);
    dense_biases_V_U->q0(dense_biases_V_q0);
    dense_array_U = new dense_layer_densehbi("dense_array_U");
    dense_array_U->clk(ap_clk);
    dense_array_U->reset(ap_rst);
    dense_array_U->address0(dense_array_address0);
    dense_array_U->ce0(dense_array_ce0);
    dense_array_U->we0(dense_array_we0);
    dense_array_U->d0(dense_array_d0);
    dense_array_U->q0(dense_array_q0);
    grp_soft_max_fu_252 = new soft_max("grp_soft_max_fu_252");
    grp_soft_max_fu_252->ap_clk(ap_clk);
    grp_soft_max_fu_252->ap_rst(ap_rst);
    grp_soft_max_fu_252->ap_start(grp_soft_max_fu_252_ap_start);
    grp_soft_max_fu_252->ap_done(grp_soft_max_fu_252_ap_done);
    grp_soft_max_fu_252->ap_idle(grp_soft_max_fu_252_ap_idle);
    grp_soft_max_fu_252->ap_ready(grp_soft_max_fu_252_ap_ready);
    grp_soft_max_fu_252->dense_array_address0(grp_soft_max_fu_252_dense_array_address0);
    grp_soft_max_fu_252->dense_array_ce0(grp_soft_max_fu_252_dense_array_ce0);
    grp_soft_max_fu_252->dense_array_q0(dense_array_q0);
    grp_soft_max_fu_252->pred_V_V_TDATA(grp_soft_max_fu_252_pred_V_V_TDATA);
    grp_soft_max_fu_252->pred_V_V_TVALID(grp_soft_max_fu_252_pred_V_V_TVALID);
    grp_soft_max_fu_252->pred_V_V_TREADY(grp_soft_max_fu_252_pred_V_V_TREADY);
    cnn_fadd_32ns_32nbkb_U48 = new cnn_fadd_32ns_32nbkb<1,4,32,32,32>("cnn_fadd_32ns_32nbkb_U48");
    cnn_fadd_32ns_32nbkb_U48->clk(ap_clk);
    cnn_fadd_32ns_32nbkb_U48->reset(ap_rst);
    cnn_fadd_32ns_32nbkb_U48->din0(w_sum_0_reg_229);
    cnn_fadd_32ns_32nbkb_U48->din1(grp_fu_259_p1);
    cnn_fadd_32ns_32nbkb_U48->ce(ap_var_for_const0);
    cnn_fadd_32ns_32nbkb_U48->dout(grp_fu_259_p2);
    cnn_mul_mul_14ns_ibs_U49 = new cnn_mul_mul_14ns_ibs<1,1,14,11,25>("cnn_mul_mul_14ns_ibs_U49");
    cnn_mul_mul_14ns_ibs_U49->din0(mul_ln941_fu_932_p0);
    cnn_mul_mul_14ns_ibs_U49->din1(dense_weights_V_q0);
    cnn_mul_mul_14ns_ibs_U49->dout(mul_ln941_fu_932_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_1_fu_772_p2);
    sensitive << ( icmp_ln947_fu_735_p2 );
    sensitive << ( icmp_ln947_1_fu_766_p2 );

    SC_METHOD(thread_a_fu_497_p2);
    sensitive << ( icmp_ln947_3_fu_465_p2 );
    sensitive << ( icmp_ln947_2_fu_491_p2 );

    SC_METHOD(thread_add_ln1116_1_fu_352_p2);
    sensitive << ( zext_ln19_reg_966 );
    sensitive << ( add_ln1116_fu_346_p2 );

    SC_METHOD(thread_add_ln1116_fu_346_p2);
    sensitive << ( zext_ln1116_fu_330_p1 );
    sensitive << ( zext_ln1116_1_fu_342_p1 );

    SC_METHOD(thread_add_ln13_fu_264_p2);
    sensitive << ( phi_ln13_reg_207 );

    SC_METHOD(thread_add_ln949_1_fu_517_p2);
    sensitive << ( trunc_ln944_1_reg_1032 );

    SC_METHOD(thread_add_ln949_fu_792_p2);
    sensitive << ( trunc_ln944_fu_715_p1 );

    SC_METHOD(thread_add_ln958_1_fu_834_p2);
    sensitive << ( sub_ln944_1_reg_1084 );

    SC_METHOD(thread_add_ln958_fu_558_p2);
    sensitive << ( sub_ln944_reg_1025 );

    SC_METHOD(thread_add_ln964_1_fu_627_p2);
    sensitive << ( sub_ln964_1_fu_622_p2 );
    sensitive << ( select_ln964_1_fu_615_p3 );

    SC_METHOD(thread_add_ln964_fu_903_p2);
    sensitive << ( select_ln964_fu_890_p3 );
    sensitive << ( sub_ln964_fu_898_p2 );

    SC_METHOD(thread_and_ln949_1_fu_529_p2);
    sensitive << ( p_Result_11_fu_522_p3 );
    sensitive << ( xor_ln949_1_fu_511_p2 );

    SC_METHOD(thread_and_ln949_fu_805_p2);
    sensitive << ( p_Result_6_fu_798_p3 );
    sensitive << ( xor_ln949_fu_786_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_soft_max_fu_252_ap_done );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_soft_max_fu_252_ap_done );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_bitcast_ln739_1_fu_928_p1);
    sensitive << ( p_Result_18_reg_1100 );

    SC_METHOD(thread_bitcast_ln739_fu_652_p1);
    sensitive << ( p_Result_15_fu_640_p5 );

    SC_METHOD(thread_d_fu_291_p2);
    sensitive << ( d_0_reg_218 );

    SC_METHOD(thread_dense_array_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln936_reg_960 );
    sensitive << ( grp_soft_max_fu_252_dense_array_address0 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( zext_ln13_fu_270_p1 );

    SC_METHOD(thread_dense_array_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_soft_max_fu_252_dense_array_ce0 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_dense_array_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_reg_1110 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_dense_array_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_dense_biases_V_address0);
    sensitive << ( zext_ln936_reg_960 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_dense_biases_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_dense_weights_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln1116_2_fu_357_p1 );

    SC_METHOD(thread_dense_weights_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_f_fu_311_p2);
    sensitive << ( f_0_reg_241 );

    SC_METHOD(thread_flat_array_V_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln21_fu_317_p1 );

    SC_METHOD(thread_flat_array_V_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_259_p1);
    sensitive << ( select_ln935_reg_1057 );
    sensitive << ( bitcast_ln739_1_fu_928_p1 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_grp_soft_max_fu_252_ap_start);
    sensitive << ( grp_soft_max_fu_252_ap_start_reg );

    SC_METHOD(thread_grp_soft_max_fu_252_pred_V_V_TREADY);
    sensitive << ( prediction_V_V_TREADY );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_icmp_ln13_fu_275_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( phi_ln13_reg_207 );

    SC_METHOD(thread_icmp_ln15_fu_285_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( d_0_reg_218 );

    SC_METHOD(thread_icmp_ln19_fu_305_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( f_0_reg_241 );

    SC_METHOD(thread_icmp_ln935_fu_386_p2);
    sensitive << ( mul_ln941_reg_1000 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_icmp_ln947_1_fu_766_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( p_Result_5_fu_761_p2 );

    SC_METHOD(thread_icmp_ln947_2_fu_491_p2);
    sensitive << ( icmp_ln935_reg_1013 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_Result_10_fu_486_p2 );

    SC_METHOD(thread_icmp_ln947_3_fu_465_p2);
    sensitive << ( icmp_ln935_reg_1013 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_15_fu_455_p4 );

    SC_METHOD(thread_icmp_ln947_fu_735_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_11_fu_725_p4 );

    SC_METHOD(thread_icmp_ln958_1_fu_825_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( lsb_index_1_fu_719_p2 );

    SC_METHOD(thread_icmp_ln958_fu_552_p2);
    sensitive << ( icmp_ln935_reg_1013 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( lsb_index_fu_450_p2 );

    SC_METHOD(thread_l_1_fu_698_p3);
    sensitive << ( p_Result_17_fu_690_p3 );

    SC_METHOD(thread_l_fu_424_p3);
    sensitive << ( p_Result_14_fu_416_p3 );

    SC_METHOD(thread_lsb_index_1_fu_719_p2);
    sensitive << ( sub_ln944_1_fu_710_p2 );

    SC_METHOD(thread_lsb_index_fu_450_p2);
    sensitive << ( sub_ln944_reg_1025 );

    SC_METHOD(thread_lshr_ln936_fu_362_p2);
    sensitive << ( zext_ln15_reg_947 );

    SC_METHOD(thread_lshr_ln947_1_fu_480_p2);
    sensitive << ( zext_ln947_1_fu_476_p1 );

    SC_METHOD(thread_lshr_ln947_fu_755_p2);
    sensitive << ( zext_ln947_fu_751_p1 );

    SC_METHOD(thread_lshr_ln958_1_fu_839_p2);
    sensitive << ( m_1_fu_831_p1 );
    sensitive << ( add_ln958_1_fu_834_p2 );

    SC_METHOD(thread_lshr_ln958_fu_563_p2);
    sensitive << ( m_fu_549_p1 );
    sensitive << ( add_ln958_fu_558_p2 );

    SC_METHOD(thread_m_11_fu_588_p2);
    sensitive << ( or_ln_fu_541_p3 );
    sensitive << ( m_9_fu_580_p3 );

    SC_METHOD(thread_m_14_fu_612_p1);
    sensitive << ( m_4_reg_1047 );

    SC_METHOD(thread_m_15_fu_878_p1);
    sensitive << ( m_s_fu_868_p4 );

    SC_METHOD(thread_m_1_fu_831_p1);
    sensitive << ( sext_ln938_reg_1067 );

    SC_METHOD(thread_m_2_fu_856_p3);
    sensitive << ( icmp_ln958_1_reg_1095 );
    sensitive << ( lshr_ln958_1_fu_839_p2 );
    sensitive << ( shl_ln958_1_fu_850_p2 );

    SC_METHOD(thread_m_3_fu_863_p2);
    sensitive << ( or_ln949_1_reg_1090 );
    sensitive << ( m_2_fu_856_p3 );

    SC_METHOD(thread_m_9_fu_580_p3);
    sensitive << ( icmp_ln958_fu_552_p2 );
    sensitive << ( lshr_ln958_fu_563_p2 );
    sensitive << ( shl_ln958_fu_574_p2 );

    SC_METHOD(thread_m_fu_549_p1);
    sensitive << ( sext_ln938_1_reg_1018 );

    SC_METHOD(thread_m_s_fu_868_p4);
    sensitive << ( m_3_fu_863_p2 );

    SC_METHOD(thread_mul_ln941_fu_932_p0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( mul_ln941_fu_932_p00 );

    SC_METHOD(thread_mul_ln941_fu_932_p00);
    sensitive << ( flat_array_V_q0 );

    SC_METHOD(thread_or_ln949_1_fu_817_p3);
    sensitive << ( or_ln949_fu_811_p2 );

    SC_METHOD(thread_or_ln949_2_fu_535_p2);
    sensitive << ( and_ln949_1_fu_529_p2 );
    sensitive << ( a_fu_497_p2 );

    SC_METHOD(thread_or_ln949_fu_811_p2);
    sensitive << ( and_ln949_fu_805_p2 );
    sensitive << ( a_1_fu_772_p2 );

    SC_METHOD(thread_or_ln_fu_541_p3);
    sensitive << ( or_ln949_2_fu_535_p2 );

    SC_METHOD(thread_p_Result_10_fu_486_p2);
    sensitive << ( sext_ln938_1_reg_1018 );
    sensitive << ( lshr_ln947_1_fu_480_p2 );

    SC_METHOD(thread_p_Result_11_fu_522_p3);
    sensitive << ( sext_ln938_1_reg_1018 );
    sensitive << ( add_ln949_1_fu_517_p2 );

    SC_METHOD(thread_p_Result_14_fu_416_p3);
    sensitive << ( p_Result_s_fu_406_p4 );

    SC_METHOD(thread_p_Result_15_fu_640_p5);
    sensitive << ( m_14_fu_612_p1 );
    sensitive << ( tmp_5_fu_633_p3 );

    SC_METHOD(thread_p_Result_16_fu_367_p1);
    sensitive << ( lshr_ln936_fu_362_p2 );

    SC_METHOD(thread_p_Result_17_fu_690_p3);
    sensitive << ( p_Result_3_fu_680_p4 );

    SC_METHOD(thread_p_Result_18_fu_916_p5);
    sensitive << ( m_15_fu_878_p1 );
    sensitive << ( tmp_4_fu_909_p3 );

    SC_METHOD(thread_p_Result_3_fu_680_p4);
    sensitive << ( sext_ln938_fu_676_p1 );

    SC_METHOD(thread_p_Result_5_fu_761_p2);
    sensitive << ( sext_ln938_reg_1067 );
    sensitive << ( lshr_ln947_fu_755_p2 );

    SC_METHOD(thread_p_Result_6_fu_798_p3);
    sensitive << ( sext_ln938_reg_1067 );
    sensitive << ( add_ln949_fu_792_p2 );

    SC_METHOD(thread_p_Result_s_fu_406_p4);
    sensitive << ( sext_ln938_1_fu_402_p1 );

    SC_METHOD(thread_prediction_V_V_TDATA);
    sensitive << ( grp_soft_max_fu_252_pred_V_V_TDATA );
    sensitive << ( grp_soft_max_fu_252_pred_V_V_TVALID );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_prediction_V_V_TVALID);
    sensitive << ( grp_soft_max_fu_252_pred_V_V_TVALID );
    sensitive << ( ap_CS_fsm_state21 );

    SC_METHOD(thread_select_ln935_fu_656_p3);
    sensitive << ( icmp_ln935_reg_1013 );
    sensitive << ( bitcast_ln739_fu_652_p1 );

    SC_METHOD(thread_select_ln964_1_fu_615_p3);
    sensitive << ( tmp_17_reg_1052 );

    SC_METHOD(thread_select_ln964_fu_890_p3);
    sensitive << ( tmp_13_fu_882_p3 );

    SC_METHOD(thread_sext_ln938_1_fu_402_p1);
    sensitive << ( tmp_V_5_fu_396_p3 );

    SC_METHOD(thread_sext_ln938_fu_676_p1);
    sensitive << ( tmp_V_7_fu_669_p3 );

    SC_METHOD(thread_shl_ln958_1_fu_850_p2);
    sensitive << ( m_1_fu_831_p1 );
    sensitive << ( sub_ln958_1_fu_845_p2 );

    SC_METHOD(thread_shl_ln958_fu_574_p2);
    sensitive << ( m_fu_549_p1 );
    sensitive << ( sub_ln958_fu_569_p2 );

    SC_METHOD(thread_sub_ln944_1_fu_710_p2);
    sensitive << ( l_1_reg_1074 );

    SC_METHOD(thread_sub_ln944_fu_432_p2);
    sensitive << ( l_fu_424_p3 );

    SC_METHOD(thread_sub_ln947_1_fu_471_p2);
    sensitive << ( trunc_ln947_1_reg_1037 );

    SC_METHOD(thread_sub_ln947_fu_745_p2);
    sensitive << ( trunc_ln947_fu_741_p1 );

    SC_METHOD(thread_sub_ln958_1_fu_845_p2);
    sensitive << ( sub_ln944_1_reg_1084 );

    SC_METHOD(thread_sub_ln958_fu_569_p2);
    sensitive << ( sub_ln944_reg_1025 );

    SC_METHOD(thread_sub_ln964_1_fu_622_p2);
    sensitive << ( trunc_ln943_1_reg_1042 );

    SC_METHOD(thread_sub_ln964_fu_898_p2);
    sensitive << ( trunc_ln943_reg_1079 );

    SC_METHOD(thread_tmp_11_fu_725_p4);
    sensitive << ( lsb_index_1_fu_719_p2 );

    SC_METHOD(thread_tmp_12_fu_778_p3);
    sensitive << ( lsb_index_1_fu_719_p2 );

    SC_METHOD(thread_tmp_13_fu_882_p3);
    sensitive << ( m_3_fu_863_p2 );

    SC_METHOD(thread_tmp_15_fu_455_p4);
    sensitive << ( lsb_index_fu_450_p2 );

    SC_METHOD(thread_tmp_16_fu_503_p3);
    sensitive << ( lsb_index_fu_450_p2 );

    SC_METHOD(thread_tmp_4_fu_909_p3);
    sensitive << ( p_Result_16_reg_994 );
    sensitive << ( add_ln964_fu_903_p2 );

    SC_METHOD(thread_tmp_5_fu_633_p3);
    sensitive << ( p_Result_13_reg_1007 );
    sensitive << ( add_ln964_1_fu_627_p2 );

    SC_METHOD(thread_tmp_9_fu_322_p3);
    sensitive << ( f_0_reg_241 );

    SC_METHOD(thread_tmp_V_3_fu_391_p2);
    sensitive << ( mul_ln941_reg_1000 );

    SC_METHOD(thread_tmp_V_5_fu_396_p3);
    sensitive << ( mul_ln941_reg_1000 );
    sensitive << ( p_Result_13_reg_1007 );
    sensitive << ( tmp_V_3_fu_391_p2 );

    SC_METHOD(thread_tmp_V_7_fu_669_p3);
    sensitive << ( dense_biases_V_q0 );
    sensitive << ( p_Result_16_reg_994 );
    sensitive << ( tmp_V_fu_663_p2 );

    SC_METHOD(thread_tmp_V_fu_663_p2);
    sensitive << ( dense_biases_V_q0 );

    SC_METHOD(thread_tmp_s_fu_334_p3);
    sensitive << ( f_0_reg_241 );

    SC_METHOD(thread_trunc_ln943_1_fu_446_p1);
    sensitive << ( l_fu_424_p3 );

    SC_METHOD(thread_trunc_ln943_fu_706_p1);
    sensitive << ( l_1_fu_698_p3 );

    SC_METHOD(thread_trunc_ln944_1_fu_438_p1);
    sensitive << ( sub_ln944_fu_432_p2 );

    SC_METHOD(thread_trunc_ln944_fu_715_p1);
    sensitive << ( sub_ln944_1_fu_710_p2 );

    SC_METHOD(thread_trunc_ln947_1_fu_442_p1);
    sensitive << ( sub_ln944_fu_432_p2 );

    SC_METHOD(thread_trunc_ln947_fu_741_p1);
    sensitive << ( sub_ln944_1_fu_710_p2 );

    SC_METHOD(thread_xor_ln949_1_fu_511_p2);
    sensitive << ( tmp_16_fu_503_p3 );

    SC_METHOD(thread_xor_ln949_fu_786_p2);
    sensitive << ( tmp_12_fu_778_p3 );

    SC_METHOD(thread_zext_ln1116_1_fu_342_p1);
    sensitive << ( tmp_s_fu_334_p3 );

    SC_METHOD(thread_zext_ln1116_2_fu_357_p1);
    sensitive << ( add_ln1116_1_fu_352_p2 );

    SC_METHOD(thread_zext_ln1116_fu_330_p1);
    sensitive << ( tmp_9_fu_322_p3 );

    SC_METHOD(thread_zext_ln13_fu_270_p1);
    sensitive << ( phi_ln13_reg_207 );

    SC_METHOD(thread_zext_ln15_fu_281_p1);
    sensitive << ( d_0_reg_218 );

    SC_METHOD(thread_zext_ln19_fu_301_p1);
    sensitive << ( d_0_reg_218 );

    SC_METHOD(thread_zext_ln21_fu_317_p1);
    sensitive << ( f_0_reg_241 );

    SC_METHOD(thread_zext_ln936_fu_297_p1);
    sensitive << ( d_0_reg_218 );

    SC_METHOD(thread_zext_ln947_1_fu_476_p1);
    sensitive << ( sub_ln947_1_fu_471_p2 );

    SC_METHOD(thread_zext_ln947_fu_751_p1);
    sensitive << ( sub_ln947_fu_745_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln15_fu_285_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln19_fu_305_p2 );
    sensitive << ( grp_soft_max_fu_252_ap_done );
    sensitive << ( icmp_ln13_fu_275_p2 );
    sensitive << ( ap_CS_fsm_state21 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000001";
    grp_soft_max_fu_252_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_layer_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, flat_array_V_address0, "(port)flat_array_V_address0");
    sc_trace(mVcdFile, flat_array_V_ce0, "(port)flat_array_V_ce0");
    sc_trace(mVcdFile, flat_array_V_q0, "(port)flat_array_V_q0");
    sc_trace(mVcdFile, prediction_V_V_TDATA, "(port)prediction_V_V_TDATA");
    sc_trace(mVcdFile, prediction_V_V_TVALID, "(port)prediction_V_V_TVALID");
    sc_trace(mVcdFile, prediction_V_V_TREADY, "(port)prediction_V_V_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, dense_weights_V_address0, "dense_weights_V_address0");
    sc_trace(mVcdFile, dense_weights_V_ce0, "dense_weights_V_ce0");
    sc_trace(mVcdFile, dense_weights_V_q0, "dense_weights_V_q0");
    sc_trace(mVcdFile, dense_biases_V_address0, "dense_biases_V_address0");
    sc_trace(mVcdFile, dense_biases_V_ce0, "dense_biases_V_ce0");
    sc_trace(mVcdFile, dense_biases_V_q0, "dense_biases_V_q0");
    sc_trace(mVcdFile, add_ln13_fu_264_p2, "add_ln13_fu_264_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln15_fu_281_p1, "zext_ln15_fu_281_p1");
    sc_trace(mVcdFile, zext_ln15_reg_947, "zext_ln15_reg_947");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, d_fu_291_p2, "d_fu_291_p2");
    sc_trace(mVcdFile, d_reg_955, "d_reg_955");
    sc_trace(mVcdFile, zext_ln936_fu_297_p1, "zext_ln936_fu_297_p1");
    sc_trace(mVcdFile, zext_ln936_reg_960, "zext_ln936_reg_960");
    sc_trace(mVcdFile, icmp_ln15_fu_285_p2, "icmp_ln15_fu_285_p2");
    sc_trace(mVcdFile, zext_ln19_fu_301_p1, "zext_ln19_fu_301_p1");
    sc_trace(mVcdFile, zext_ln19_reg_966, "zext_ln19_reg_966");
    sc_trace(mVcdFile, f_fu_311_p2, "f_fu_311_p2");
    sc_trace(mVcdFile, f_reg_974, "f_reg_974");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln19_fu_305_p2, "icmp_ln19_fu_305_p2");
    sc_trace(mVcdFile, p_Result_16_fu_367_p1, "p_Result_16_fu_367_p1");
    sc_trace(mVcdFile, p_Result_16_reg_994, "p_Result_16_reg_994");
    sc_trace(mVcdFile, mul_ln941_fu_932_p2, "mul_ln941_fu_932_p2");
    sc_trace(mVcdFile, mul_ln941_reg_1000, "mul_ln941_reg_1000");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, p_Result_13_reg_1007, "p_Result_13_reg_1007");
    sc_trace(mVcdFile, icmp_ln935_fu_386_p2, "icmp_ln935_fu_386_p2");
    sc_trace(mVcdFile, icmp_ln935_reg_1013, "icmp_ln935_reg_1013");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, sext_ln938_1_fu_402_p1, "sext_ln938_1_fu_402_p1");
    sc_trace(mVcdFile, sext_ln938_1_reg_1018, "sext_ln938_1_reg_1018");
    sc_trace(mVcdFile, sub_ln944_fu_432_p2, "sub_ln944_fu_432_p2");
    sc_trace(mVcdFile, sub_ln944_reg_1025, "sub_ln944_reg_1025");
    sc_trace(mVcdFile, trunc_ln944_1_fu_438_p1, "trunc_ln944_1_fu_438_p1");
    sc_trace(mVcdFile, trunc_ln944_1_reg_1032, "trunc_ln944_1_reg_1032");
    sc_trace(mVcdFile, trunc_ln947_1_fu_442_p1, "trunc_ln947_1_fu_442_p1");
    sc_trace(mVcdFile, trunc_ln947_1_reg_1037, "trunc_ln947_1_reg_1037");
    sc_trace(mVcdFile, trunc_ln943_1_fu_446_p1, "trunc_ln943_1_fu_446_p1");
    sc_trace(mVcdFile, trunc_ln943_1_reg_1042, "trunc_ln943_1_reg_1042");
    sc_trace(mVcdFile, m_4_reg_1047, "m_4_reg_1047");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_17_reg_1052, "tmp_17_reg_1052");
    sc_trace(mVcdFile, select_ln935_fu_656_p3, "select_ln935_fu_656_p3");
    sc_trace(mVcdFile, select_ln935_reg_1057, "select_ln935_reg_1057");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_259_p2, "grp_fu_259_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, sext_ln938_fu_676_p1, "sext_ln938_fu_676_p1");
    sc_trace(mVcdFile, sext_ln938_reg_1067, "sext_ln938_reg_1067");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, l_1_fu_698_p3, "l_1_fu_698_p3");
    sc_trace(mVcdFile, l_1_reg_1074, "l_1_reg_1074");
    sc_trace(mVcdFile, trunc_ln943_fu_706_p1, "trunc_ln943_fu_706_p1");
    sc_trace(mVcdFile, trunc_ln943_reg_1079, "trunc_ln943_reg_1079");
    sc_trace(mVcdFile, sub_ln944_1_fu_710_p2, "sub_ln944_1_fu_710_p2");
    sc_trace(mVcdFile, sub_ln944_1_reg_1084, "sub_ln944_1_reg_1084");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, or_ln949_1_fu_817_p3, "or_ln949_1_fu_817_p3");
    sc_trace(mVcdFile, or_ln949_1_reg_1090, "or_ln949_1_reg_1090");
    sc_trace(mVcdFile, icmp_ln958_1_fu_825_p2, "icmp_ln958_1_fu_825_p2");
    sc_trace(mVcdFile, icmp_ln958_1_reg_1095, "icmp_ln958_1_reg_1095");
    sc_trace(mVcdFile, p_Result_18_fu_916_p5, "p_Result_18_fu_916_p5");
    sc_trace(mVcdFile, p_Result_18_reg_1100, "p_Result_18_reg_1100");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, bitcast_ln739_1_fu_928_p1, "bitcast_ln739_1_fu_928_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, tmp_reg_1110, "tmp_reg_1110");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, dense_array_address0, "dense_array_address0");
    sc_trace(mVcdFile, dense_array_ce0, "dense_array_ce0");
    sc_trace(mVcdFile, dense_array_we0, "dense_array_we0");
    sc_trace(mVcdFile, dense_array_d0, "dense_array_d0");
    sc_trace(mVcdFile, dense_array_q0, "dense_array_q0");
    sc_trace(mVcdFile, grp_soft_max_fu_252_ap_start, "grp_soft_max_fu_252_ap_start");
    sc_trace(mVcdFile, grp_soft_max_fu_252_ap_done, "grp_soft_max_fu_252_ap_done");
    sc_trace(mVcdFile, grp_soft_max_fu_252_ap_idle, "grp_soft_max_fu_252_ap_idle");
    sc_trace(mVcdFile, grp_soft_max_fu_252_ap_ready, "grp_soft_max_fu_252_ap_ready");
    sc_trace(mVcdFile, grp_soft_max_fu_252_dense_array_address0, "grp_soft_max_fu_252_dense_array_address0");
    sc_trace(mVcdFile, grp_soft_max_fu_252_dense_array_ce0, "grp_soft_max_fu_252_dense_array_ce0");
    sc_trace(mVcdFile, grp_soft_max_fu_252_pred_V_V_TDATA, "grp_soft_max_fu_252_pred_V_V_TDATA");
    sc_trace(mVcdFile, grp_soft_max_fu_252_pred_V_V_TVALID, "grp_soft_max_fu_252_pred_V_V_TVALID");
    sc_trace(mVcdFile, grp_soft_max_fu_252_pred_V_V_TREADY, "grp_soft_max_fu_252_pred_V_V_TREADY");
    sc_trace(mVcdFile, phi_ln13_reg_207, "phi_ln13_reg_207");
    sc_trace(mVcdFile, icmp_ln13_fu_275_p2, "icmp_ln13_fu_275_p2");
    sc_trace(mVcdFile, d_0_reg_218, "d_0_reg_218");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, w_sum_0_reg_229, "w_sum_0_reg_229");
    sc_trace(mVcdFile, f_0_reg_241, "f_0_reg_241");
    sc_trace(mVcdFile, grp_soft_max_fu_252_ap_start_reg, "grp_soft_max_fu_252_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, zext_ln13_fu_270_p1, "zext_ln13_fu_270_p1");
    sc_trace(mVcdFile, zext_ln1116_2_fu_357_p1, "zext_ln1116_2_fu_357_p1");
    sc_trace(mVcdFile, zext_ln21_fu_317_p1, "zext_ln21_fu_317_p1");
    sc_trace(mVcdFile, grp_fu_259_p1, "grp_fu_259_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_9_fu_322_p3, "tmp_9_fu_322_p3");
    sc_trace(mVcdFile, tmp_s_fu_334_p3, "tmp_s_fu_334_p3");
    sc_trace(mVcdFile, zext_ln1116_fu_330_p1, "zext_ln1116_fu_330_p1");
    sc_trace(mVcdFile, zext_ln1116_1_fu_342_p1, "zext_ln1116_1_fu_342_p1");
    sc_trace(mVcdFile, add_ln1116_fu_346_p2, "add_ln1116_fu_346_p2");
    sc_trace(mVcdFile, add_ln1116_1_fu_352_p2, "add_ln1116_1_fu_352_p2");
    sc_trace(mVcdFile, lshr_ln936_fu_362_p2, "lshr_ln936_fu_362_p2");
    sc_trace(mVcdFile, tmp_V_3_fu_391_p2, "tmp_V_3_fu_391_p2");
    sc_trace(mVcdFile, tmp_V_5_fu_396_p3, "tmp_V_5_fu_396_p3");
    sc_trace(mVcdFile, p_Result_s_fu_406_p4, "p_Result_s_fu_406_p4");
    sc_trace(mVcdFile, p_Result_14_fu_416_p3, "p_Result_14_fu_416_p3");
    sc_trace(mVcdFile, l_fu_424_p3, "l_fu_424_p3");
    sc_trace(mVcdFile, lsb_index_fu_450_p2, "lsb_index_fu_450_p2");
    sc_trace(mVcdFile, tmp_15_fu_455_p4, "tmp_15_fu_455_p4");
    sc_trace(mVcdFile, sub_ln947_1_fu_471_p2, "sub_ln947_1_fu_471_p2");
    sc_trace(mVcdFile, zext_ln947_1_fu_476_p1, "zext_ln947_1_fu_476_p1");
    sc_trace(mVcdFile, lshr_ln947_1_fu_480_p2, "lshr_ln947_1_fu_480_p2");
    sc_trace(mVcdFile, p_Result_10_fu_486_p2, "p_Result_10_fu_486_p2");
    sc_trace(mVcdFile, icmp_ln947_3_fu_465_p2, "icmp_ln947_3_fu_465_p2");
    sc_trace(mVcdFile, icmp_ln947_2_fu_491_p2, "icmp_ln947_2_fu_491_p2");
    sc_trace(mVcdFile, tmp_16_fu_503_p3, "tmp_16_fu_503_p3");
    sc_trace(mVcdFile, add_ln949_1_fu_517_p2, "add_ln949_1_fu_517_p2");
    sc_trace(mVcdFile, p_Result_11_fu_522_p3, "p_Result_11_fu_522_p3");
    sc_trace(mVcdFile, xor_ln949_1_fu_511_p2, "xor_ln949_1_fu_511_p2");
    sc_trace(mVcdFile, and_ln949_1_fu_529_p2, "and_ln949_1_fu_529_p2");
    sc_trace(mVcdFile, a_fu_497_p2, "a_fu_497_p2");
    sc_trace(mVcdFile, or_ln949_2_fu_535_p2, "or_ln949_2_fu_535_p2");
    sc_trace(mVcdFile, m_fu_549_p1, "m_fu_549_p1");
    sc_trace(mVcdFile, add_ln958_fu_558_p2, "add_ln958_fu_558_p2");
    sc_trace(mVcdFile, sub_ln958_fu_569_p2, "sub_ln958_fu_569_p2");
    sc_trace(mVcdFile, icmp_ln958_fu_552_p2, "icmp_ln958_fu_552_p2");
    sc_trace(mVcdFile, lshr_ln958_fu_563_p2, "lshr_ln958_fu_563_p2");
    sc_trace(mVcdFile, shl_ln958_fu_574_p2, "shl_ln958_fu_574_p2");
    sc_trace(mVcdFile, or_ln_fu_541_p3, "or_ln_fu_541_p3");
    sc_trace(mVcdFile, m_9_fu_580_p3, "m_9_fu_580_p3");
    sc_trace(mVcdFile, m_11_fu_588_p2, "m_11_fu_588_p2");
    sc_trace(mVcdFile, sub_ln964_1_fu_622_p2, "sub_ln964_1_fu_622_p2");
    sc_trace(mVcdFile, select_ln964_1_fu_615_p3, "select_ln964_1_fu_615_p3");
    sc_trace(mVcdFile, add_ln964_1_fu_627_p2, "add_ln964_1_fu_627_p2");
    sc_trace(mVcdFile, m_14_fu_612_p1, "m_14_fu_612_p1");
    sc_trace(mVcdFile, tmp_5_fu_633_p3, "tmp_5_fu_633_p3");
    sc_trace(mVcdFile, p_Result_15_fu_640_p5, "p_Result_15_fu_640_p5");
    sc_trace(mVcdFile, bitcast_ln739_fu_652_p1, "bitcast_ln739_fu_652_p1");
    sc_trace(mVcdFile, tmp_V_fu_663_p2, "tmp_V_fu_663_p2");
    sc_trace(mVcdFile, tmp_V_7_fu_669_p3, "tmp_V_7_fu_669_p3");
    sc_trace(mVcdFile, p_Result_3_fu_680_p4, "p_Result_3_fu_680_p4");
    sc_trace(mVcdFile, p_Result_17_fu_690_p3, "p_Result_17_fu_690_p3");
    sc_trace(mVcdFile, lsb_index_1_fu_719_p2, "lsb_index_1_fu_719_p2");
    sc_trace(mVcdFile, tmp_11_fu_725_p4, "tmp_11_fu_725_p4");
    sc_trace(mVcdFile, trunc_ln947_fu_741_p1, "trunc_ln947_fu_741_p1");
    sc_trace(mVcdFile, sub_ln947_fu_745_p2, "sub_ln947_fu_745_p2");
    sc_trace(mVcdFile, zext_ln947_fu_751_p1, "zext_ln947_fu_751_p1");
    sc_trace(mVcdFile, lshr_ln947_fu_755_p2, "lshr_ln947_fu_755_p2");
    sc_trace(mVcdFile, p_Result_5_fu_761_p2, "p_Result_5_fu_761_p2");
    sc_trace(mVcdFile, icmp_ln947_fu_735_p2, "icmp_ln947_fu_735_p2");
    sc_trace(mVcdFile, icmp_ln947_1_fu_766_p2, "icmp_ln947_1_fu_766_p2");
    sc_trace(mVcdFile, tmp_12_fu_778_p3, "tmp_12_fu_778_p3");
    sc_trace(mVcdFile, trunc_ln944_fu_715_p1, "trunc_ln944_fu_715_p1");
    sc_trace(mVcdFile, add_ln949_fu_792_p2, "add_ln949_fu_792_p2");
    sc_trace(mVcdFile, p_Result_6_fu_798_p3, "p_Result_6_fu_798_p3");
    sc_trace(mVcdFile, xor_ln949_fu_786_p2, "xor_ln949_fu_786_p2");
    sc_trace(mVcdFile, and_ln949_fu_805_p2, "and_ln949_fu_805_p2");
    sc_trace(mVcdFile, a_1_fu_772_p2, "a_1_fu_772_p2");
    sc_trace(mVcdFile, or_ln949_fu_811_p2, "or_ln949_fu_811_p2");
    sc_trace(mVcdFile, m_1_fu_831_p1, "m_1_fu_831_p1");
    sc_trace(mVcdFile, add_ln958_1_fu_834_p2, "add_ln958_1_fu_834_p2");
    sc_trace(mVcdFile, sub_ln958_1_fu_845_p2, "sub_ln958_1_fu_845_p2");
    sc_trace(mVcdFile, lshr_ln958_1_fu_839_p2, "lshr_ln958_1_fu_839_p2");
    sc_trace(mVcdFile, shl_ln958_1_fu_850_p2, "shl_ln958_1_fu_850_p2");
    sc_trace(mVcdFile, m_2_fu_856_p3, "m_2_fu_856_p3");
    sc_trace(mVcdFile, m_3_fu_863_p2, "m_3_fu_863_p2");
    sc_trace(mVcdFile, m_s_fu_868_p4, "m_s_fu_868_p4");
    sc_trace(mVcdFile, tmp_13_fu_882_p3, "tmp_13_fu_882_p3");
    sc_trace(mVcdFile, select_ln964_fu_890_p3, "select_ln964_fu_890_p3");
    sc_trace(mVcdFile, sub_ln964_fu_898_p2, "sub_ln964_fu_898_p2");
    sc_trace(mVcdFile, add_ln964_fu_903_p2, "add_ln964_fu_903_p2");
    sc_trace(mVcdFile, m_15_fu_878_p1, "m_15_fu_878_p1");
    sc_trace(mVcdFile, tmp_4_fu_909_p3, "tmp_4_fu_909_p3");
    sc_trace(mVcdFile, mul_ln941_fu_932_p0, "mul_ln941_fu_932_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln941_fu_932_p00, "mul_ln941_fu_932_p00");
#endif

    }
}

dense_layer::~dense_layer() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dense_weights_V_U;
    delete dense_biases_V_U;
    delete dense_array_U;
    delete grp_soft_max_fu_252;
    delete cnn_fadd_32ns_32nbkb_U48;
    delete cnn_mul_mul_14ns_ibs_U49;
}

void dense_layer::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dense_layer::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln13_fu_275_p2.read()))) {
        d_0_reg_218 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        d_0_reg_218 = d_reg_955.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln15_fu_285_p2.read(), ap_const_lv1_0))) {
        f_0_reg_241 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        f_0_reg_241 = f_reg_974.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_soft_max_fu_252_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln15_fu_285_p2.read(), ap_const_lv1_1))) {
            grp_soft_max_fu_252_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_soft_max_fu_252_ap_ready.read())) {
            grp_soft_max_fu_252_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln13_fu_275_p2.read()))) {
        phi_ln13_reg_207 = add_ln13_fu_264_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_ln13_reg_207 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln15_fu_285_p2.read(), ap_const_lv1_0))) {
        w_sum_0_reg_229 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        w_sum_0_reg_229 = grp_fu_259_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        d_reg_955 = d_fu_291_p2.read();
        zext_ln15_reg_947 = zext_ln15_fu_281_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        f_reg_974 = f_fu_311_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        icmp_ln935_reg_1013 = icmp_ln935_fu_386_p2.read();
        sext_ln938_1_reg_1018 = sext_ln938_1_fu_402_p1.read();
        sub_ln944_reg_1025 = sub_ln944_fu_432_p2.read();
        trunc_ln943_1_reg_1042 = trunc_ln943_1_fu_446_p1.read();
        trunc_ln944_1_reg_1032 = trunc_ln944_1_fu_438_p1.read();
        trunc_ln947_1_reg_1037 = trunc_ln947_1_fu_442_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        icmp_ln958_1_reg_1095 = icmp_ln958_1_fu_825_p2.read();
        or_ln949_1_reg_1090 = or_ln949_1_fu_817_p3.read();
        sub_ln944_1_reg_1084 = sub_ln944_1_fu_710_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        l_1_reg_1074 = l_1_fu_698_p3.read();
        sext_ln938_reg_1067 = sext_ln938_fu_676_p1.read();
        trunc_ln943_reg_1079 = trunc_ln943_fu_706_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_1013.read()))) {
        m_4_reg_1047 = m_11_fu_588_p2.read().range(31, 1);
        tmp_17_reg_1052 = m_11_fu_588_p2.read().range(25, 25);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        mul_ln941_reg_1000 = mul_ln941_fu_932_p2.read();
        p_Result_13_reg_1007 = mul_ln941_fu_932_p2.read().range(24, 24);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln19_fu_305_p2.read(), ap_const_lv1_1))) {
        p_Result_16_reg_994 = p_Result_16_fu_367_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        p_Result_18_reg_1100 = p_Result_18_fu_916_p5.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        select_ln935_reg_1057 = select_ln935_fu_656_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        tmp_reg_1110 = grp_fu_259_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_285_p2.read(), ap_const_lv1_0))) {
        zext_ln19_reg_966 = zext_ln19_fu_301_p1.read();
        zext_ln936_reg_960 = zext_ln936_fu_297_p1.read();
    }
}

void dense_layer::thread_a_1_fu_772_p2() {
    a_1_fu_772_p2 = (icmp_ln947_fu_735_p2.read() & icmp_ln947_1_fu_766_p2.read());
}

void dense_layer::thread_a_fu_497_p2() {
    a_fu_497_p2 = (icmp_ln947_3_fu_465_p2.read() & icmp_ln947_2_fu_491_p2.read());
}

void dense_layer::thread_add_ln1116_1_fu_352_p2() {
    add_ln1116_1_fu_352_p2 = (!zext_ln19_reg_966.read().is_01() || !add_ln1116_fu_346_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln19_reg_966.read()) + sc_biguint<12>(add_ln1116_fu_346_p2.read()));
}

void dense_layer::thread_add_ln1116_fu_346_p2() {
    add_ln1116_fu_346_p2 = (!zext_ln1116_fu_330_p1.read().is_01() || !zext_ln1116_1_fu_342_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln1116_fu_330_p1.read()) + sc_biguint<12>(zext_ln1116_1_fu_342_p1.read()));
}

void dense_layer::thread_add_ln13_fu_264_p2() {
    add_ln13_fu_264_p2 = (!phi_ln13_reg_207.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(phi_ln13_reg_207.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dense_layer::thread_add_ln949_1_fu_517_p2() {
    add_ln949_1_fu_517_p2 = (!ap_const_lv30_3FFFFFE8.is_01() || !trunc_ln944_1_reg_1032.read().is_01())? sc_lv<30>(): (sc_bigint<30>(ap_const_lv30_3FFFFFE8) + sc_biguint<30>(trunc_ln944_1_reg_1032.read()));
}

void dense_layer::thread_add_ln949_fu_792_p2() {
    add_ln949_fu_792_p2 = (!ap_const_lv15_7FE8.is_01() || !trunc_ln944_fu_715_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(ap_const_lv15_7FE8) + sc_biguint<15>(trunc_ln944_fu_715_p1.read()));
}

void dense_layer::thread_add_ln958_1_fu_834_p2() {
    add_ln958_1_fu_834_p2 = (!ap_const_lv32_FFFFFFE7.is_01() || !sub_ln944_1_reg_1084.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE7) + sc_biguint<32>(sub_ln944_1_reg_1084.read()));
}

void dense_layer::thread_add_ln958_fu_558_p2() {
    add_ln958_fu_558_p2 = (!ap_const_lv32_FFFFFFE7.is_01() || !sub_ln944_reg_1025.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE7) + sc_biguint<32>(sub_ln944_reg_1025.read()));
}

void dense_layer::thread_add_ln964_1_fu_627_p2() {
    add_ln964_1_fu_627_p2 = (!sub_ln964_1_fu_622_p2.read().is_01() || !select_ln964_1_fu_615_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sub_ln964_1_fu_622_p2.read()) + sc_biguint<8>(select_ln964_1_fu_615_p3.read()));
}

void dense_layer::thread_add_ln964_fu_903_p2() {
    add_ln964_fu_903_p2 = (!select_ln964_fu_890_p3.read().is_01() || !sub_ln964_fu_898_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(select_ln964_fu_890_p3.read()) + sc_biguint<8>(sub_ln964_fu_898_p2.read()));
}

void dense_layer::thread_and_ln949_1_fu_529_p2() {
    and_ln949_1_fu_529_p2 = (p_Result_11_fu_522_p3.read() & xor_ln949_1_fu_511_p2.read());
}

void dense_layer::thread_and_ln949_fu_805_p2() {
    and_ln949_fu_805_p2 = (p_Result_6_fu_798_p3.read() & xor_ln949_fu_786_p2.read());
}

void dense_layer::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_layer::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void dense_layer::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void dense_layer::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void dense_layer::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void dense_layer::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void dense_layer::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void dense_layer::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dense_layer::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void dense_layer::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void dense_layer::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dense_layer::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void dense_layer::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void dense_layer::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void dense_layer::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void dense_layer::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void dense_layer::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void dense_layer::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
          esl_seteq<1,1,1>(grp_soft_max_fu_252_ap_done.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dense_layer::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_layer::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
         esl_seteq<1,1,1>(grp_soft_max_fu_252_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_layer::thread_bitcast_ln739_1_fu_928_p1() {
    bitcast_ln739_1_fu_928_p1 = p_Result_18_reg_1100.read();
}

void dense_layer::thread_bitcast_ln739_fu_652_p1() {
    bitcast_ln739_fu_652_p1 = p_Result_15_fu_640_p5.read();
}

void dense_layer::thread_d_fu_291_p2() {
    d_fu_291_p2 = (!d_0_reg_218.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(d_0_reg_218.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dense_layer::thread_dense_array_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        dense_array_address0 =  (sc_lv<4>) (zext_ln936_reg_960.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        dense_array_address0 =  (sc_lv<4>) (zext_ln13_fu_270_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        dense_array_address0 = grp_soft_max_fu_252_dense_array_address0.read();
    } else {
        dense_array_address0 = "XXXX";
    }
}

void dense_layer::thread_dense_array_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        dense_array_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        dense_array_ce0 = grp_soft_max_fu_252_dense_array_ce0.read();
    } else {
        dense_array_ce0 = ap_const_logic_0;
    }
}

void dense_layer::thread_dense_array_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        dense_array_d0 = tmp_reg_1110.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        dense_array_d0 = ap_const_lv32_0;
    } else {
        dense_array_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dense_layer::thread_dense_array_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        dense_array_we0 = ap_const_logic_1;
    } else {
        dense_array_we0 = ap_const_logic_0;
    }
}

void dense_layer::thread_dense_biases_V_address0() {
    dense_biases_V_address0 =  (sc_lv<4>) (zext_ln936_reg_960.read());
}

void dense_layer::thread_dense_biases_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        dense_biases_V_ce0 = ap_const_logic_1;
    } else {
        dense_biases_V_ce0 = ap_const_logic_0;
    }
}

void dense_layer::thread_dense_weights_V_address0() {
    dense_weights_V_address0 =  (sc_lv<11>) (zext_ln1116_2_fu_357_p1.read());
}

void dense_layer::thread_dense_weights_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        dense_weights_V_ce0 = ap_const_logic_1;
    } else {
        dense_weights_V_ce0 = ap_const_logic_0;
    }
}

void dense_layer::thread_f_fu_311_p2() {
    f_fu_311_p2 = (!f_0_reg_241.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(f_0_reg_241.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dense_layer::thread_flat_array_V_address0() {
    flat_array_V_address0 =  (sc_lv<8>) (zext_ln21_fu_317_p1.read());
}

void dense_layer::thread_flat_array_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        flat_array_V_ce0 = ap_const_logic_1;
    } else {
        flat_array_V_ce0 = ap_const_logic_0;
    }
}

void dense_layer::thread_grp_fu_259_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        grp_fu_259_p1 = bitcast_ln739_1_fu_928_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        grp_fu_259_p1 = select_ln935_reg_1057.read();
    } else {
        grp_fu_259_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dense_layer::thread_grp_soft_max_fu_252_ap_start() {
    grp_soft_max_fu_252_ap_start = grp_soft_max_fu_252_ap_start_reg.read();
}

void dense_layer::thread_grp_soft_max_fu_252_pred_V_V_TREADY() {
    grp_soft_max_fu_252_pred_V_V_TREADY = (prediction_V_V_TREADY.read() & ap_CS_fsm_state21.read());
}

void dense_layer::thread_icmp_ln13_fu_275_p2() {
    icmp_ln13_fu_275_p2 = (!phi_ln13_reg_207.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(phi_ln13_reg_207.read() == ap_const_lv4_9);
}

void dense_layer::thread_icmp_ln15_fu_285_p2() {
    icmp_ln15_fu_285_p2 = (!d_0_reg_218.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(d_0_reg_218.read() == ap_const_lv4_A);
}

void dense_layer::thread_icmp_ln19_fu_305_p2() {
    icmp_ln19_fu_305_p2 = (!f_0_reg_241.read().is_01() || !ap_const_lv8_A0.is_01())? sc_lv<1>(): sc_lv<1>(f_0_reg_241.read() == ap_const_lv8_A0);
}

void dense_layer::thread_icmp_ln935_fu_386_p2() {
    icmp_ln935_fu_386_p2 = (!mul_ln941_reg_1000.read().is_01() || !ap_const_lv25_0.is_01())? sc_lv<1>(): sc_lv<1>(mul_ln941_reg_1000.read() == ap_const_lv25_0);
}

void dense_layer::thread_icmp_ln947_1_fu_766_p2() {
    icmp_ln947_1_fu_766_p2 = (!p_Result_5_fu_761_p2.read().is_01() || !ap_const_lv15_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_5_fu_761_p2.read() != ap_const_lv15_0);
}

void dense_layer::thread_icmp_ln947_2_fu_491_p2() {
    icmp_ln947_2_fu_491_p2 = (!p_Result_10_fu_486_p2.read().is_01() || !ap_const_lv30_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_10_fu_486_p2.read() != ap_const_lv30_0);
}

void dense_layer::thread_icmp_ln947_3_fu_465_p2() {
    icmp_ln947_3_fu_465_p2 = (!tmp_15_fu_455_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_15_fu_455_p4.read()) > sc_bigint<31>(ap_const_lv31_0));
}

void dense_layer::thread_icmp_ln947_fu_735_p2() {
    icmp_ln947_fu_735_p2 = (!tmp_11_fu_725_p4.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_11_fu_725_p4.read()) > sc_bigint<31>(ap_const_lv31_0));
}

void dense_layer::thread_icmp_ln958_1_fu_825_p2() {
    icmp_ln958_1_fu_825_p2 = (!lsb_index_1_fu_719_p2.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(lsb_index_1_fu_719_p2.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void dense_layer::thread_icmp_ln958_fu_552_p2() {
    icmp_ln958_fu_552_p2 = (!lsb_index_fu_450_p2.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(lsb_index_fu_450_p2.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void dense_layer::thread_l_1_fu_698_p3() {
    l_1_fu_698_p3 = esl_cttz<32,32>(p_Result_17_fu_690_p3.read());
}

void dense_layer::thread_l_fu_424_p3() {
    l_fu_424_p3 = esl_cttz<32,32>(p_Result_14_fu_416_p3.read());
}

void dense_layer::thread_lsb_index_1_fu_719_p2() {
    lsb_index_1_fu_719_p2 = (!ap_const_lv32_FFFFFFE8.is_01() || !sub_ln944_1_fu_710_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE8) + sc_biguint<32>(sub_ln944_1_fu_710_p2.read()));
}

void dense_layer::thread_lsb_index_fu_450_p2() {
    lsb_index_fu_450_p2 = (!ap_const_lv32_FFFFFFE8.is_01() || !sub_ln944_reg_1025.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE8) + sc_biguint<32>(sub_ln944_reg_1025.read()));
}

void dense_layer::thread_lshr_ln936_fu_362_p2() {
    lshr_ln936_fu_362_p2 = (!zext_ln15_reg_947.read().is_01())? sc_lv<10>(): ap_const_lv10_2CC >> (unsigned short)zext_ln15_reg_947.read().to_uint();
}

void dense_layer::thread_lshr_ln947_1_fu_480_p2() {
    lshr_ln947_1_fu_480_p2 = (!zext_ln947_1_fu_476_p1.read().is_01())? sc_lv<30>(): ap_const_lv30_3FFFFFFF >> (unsigned short)zext_ln947_1_fu_476_p1.read().to_uint();
}

void dense_layer::thread_lshr_ln947_fu_755_p2() {
    lshr_ln947_fu_755_p2 = (!zext_ln947_fu_751_p1.read().is_01())? sc_lv<15>(): ap_const_lv15_7FFF >> (unsigned short)zext_ln947_fu_751_p1.read().to_uint();
}

void dense_layer::thread_lshr_ln958_1_fu_839_p2() {
    lshr_ln958_1_fu_839_p2 = (!add_ln958_1_fu_834_p2.read().is_01())? sc_lv<32>(): m_1_fu_831_p1.read() >> (unsigned short)add_ln958_1_fu_834_p2.read().to_uint();
}

void dense_layer::thread_lshr_ln958_fu_563_p2() {
    lshr_ln958_fu_563_p2 = (!add_ln958_fu_558_p2.read().is_01())? sc_lv<32>(): m_fu_549_p1.read() >> (unsigned short)add_ln958_fu_558_p2.read().to_uint();
}

void dense_layer::thread_m_11_fu_588_p2() {
    m_11_fu_588_p2 = (!or_ln_fu_541_p3.read().is_01() || !m_9_fu_580_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(or_ln_fu_541_p3.read()) + sc_biguint<32>(m_9_fu_580_p3.read()));
}

void dense_layer::thread_m_14_fu_612_p1() {
    m_14_fu_612_p1 = esl_zext<32,31>(m_4_reg_1047.read());
}

void dense_layer::thread_m_15_fu_878_p1() {
    m_15_fu_878_p1 = esl_zext<32,31>(m_s_fu_868_p4.read());
}

void dense_layer::thread_m_1_fu_831_p1() {
    m_1_fu_831_p1 = esl_zext<32,15>(sext_ln938_reg_1067.read());
}

void dense_layer::thread_m_2_fu_856_p3() {
    m_2_fu_856_p3 = (!icmp_ln958_1_reg_1095.read()[0].is_01())? sc_lv<32>(): ((icmp_ln958_1_reg_1095.read()[0].to_bool())? lshr_ln958_1_fu_839_p2.read(): shl_ln958_1_fu_850_p2.read());
}

void dense_layer::thread_m_3_fu_863_p2() {
    m_3_fu_863_p2 = (!m_2_fu_856_p3.read().is_01() || !or_ln949_1_reg_1090.read().is_01())? sc_lv<32>(): (sc_biguint<32>(m_2_fu_856_p3.read()) + sc_biguint<32>(or_ln949_1_reg_1090.read()));
}

void dense_layer::thread_m_9_fu_580_p3() {
    m_9_fu_580_p3 = (!icmp_ln958_fu_552_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln958_fu_552_p2.read()[0].to_bool())? lshr_ln958_fu_563_p2.read(): shl_ln958_fu_574_p2.read());
}

void dense_layer::thread_m_fu_549_p1() {
    m_fu_549_p1 = esl_zext<32,30>(sext_ln938_1_reg_1018.read());
}

void dense_layer::thread_m_s_fu_868_p4() {
    m_s_fu_868_p4 = m_3_fu_863_p2.read().range(31, 1);
}

void dense_layer::thread_mul_ln941_fu_932_p0() {
    mul_ln941_fu_932_p0 =  (sc_lv<14>) (mul_ln941_fu_932_p00.read());
}

void dense_layer::thread_mul_ln941_fu_932_p00() {
    mul_ln941_fu_932_p00 = esl_zext<25,14>(flat_array_V_q0.read());
}

void dense_layer::thread_or_ln949_1_fu_817_p3() {
    or_ln949_1_fu_817_p3 = esl_concat<31,1>(ap_const_lv31_0, or_ln949_fu_811_p2.read());
}

void dense_layer::thread_or_ln949_2_fu_535_p2() {
    or_ln949_2_fu_535_p2 = (and_ln949_1_fu_529_p2.read() | a_fu_497_p2.read());
}

void dense_layer::thread_or_ln949_fu_811_p2() {
    or_ln949_fu_811_p2 = (and_ln949_fu_805_p2.read() | a_1_fu_772_p2.read());
}

void dense_layer::thread_or_ln_fu_541_p3() {
    or_ln_fu_541_p3 = esl_concat<31,1>(ap_const_lv31_0, or_ln949_2_fu_535_p2.read());
}

void dense_layer::thread_p_Result_10_fu_486_p2() {
    p_Result_10_fu_486_p2 = (sext_ln938_1_reg_1018.read() & lshr_ln947_1_fu_480_p2.read());
}

void dense_layer::thread_p_Result_11_fu_522_p3() {
    p_Result_11_fu_522_p3 = (!add_ln949_1_fu_517_p2.read().is_01() || sc_biguint<30>(add_ln949_1_fu_517_p2.read()).to_uint() >= 30)? sc_lv<1>(): sext_ln938_1_reg_1018.read().range(sc_biguint<30>(add_ln949_1_fu_517_p2.read()).to_uint(), sc_biguint<30>(add_ln949_1_fu_517_p2.read()).to_uint());
}

void dense_layer::thread_p_Result_14_fu_416_p3() {
    p_Result_14_fu_416_p3 = esl_concat<2,30>(ap_const_lv2_3, p_Result_s_fu_406_p4.read());
}

void dense_layer::thread_p_Result_15_fu_640_p5() {
    p_Result_15_fu_640_p5 = esl_partset<32,32,9,32,32>(m_14_fu_612_p1.read(), tmp_5_fu_633_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void dense_layer::thread_p_Result_16_fu_367_p1() {
    p_Result_16_fu_367_p1 = lshr_ln936_fu_362_p2.read().range(1-1, 0);
}

void dense_layer::thread_p_Result_17_fu_690_p3() {
    p_Result_17_fu_690_p3 = esl_concat<17,15>(ap_const_lv17_1FFFF, p_Result_3_fu_680_p4.read());
}

void dense_layer::thread_p_Result_18_fu_916_p5() {
    p_Result_18_fu_916_p5 = esl_partset<32,32,9,32,32>(m_15_fu_878_p1.read(), tmp_4_fu_909_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void dense_layer::thread_p_Result_3_fu_680_p4() {
    p_Result_3_fu_680_p4 = sext_ln938_fu_676_p1.read().range(0, 14);
}

void dense_layer::thread_p_Result_5_fu_761_p2() {
    p_Result_5_fu_761_p2 = (sext_ln938_reg_1067.read() & lshr_ln947_fu_755_p2.read());
}

void dense_layer::thread_p_Result_6_fu_798_p3() {
    p_Result_6_fu_798_p3 = (!add_ln949_fu_792_p2.read().is_01() || sc_biguint<15>(add_ln949_fu_792_p2.read()).to_uint() >= 15)? sc_lv<1>(): sext_ln938_reg_1067.read().range(sc_biguint<15>(add_ln949_fu_792_p2.read()).to_uint(), sc_biguint<15>(add_ln949_fu_792_p2.read()).to_uint());
}

void dense_layer::thread_p_Result_s_fu_406_p4() {
    p_Result_s_fu_406_p4 = sext_ln938_1_fu_402_p1.read().range(0, 29);
}

void dense_layer::thread_prediction_V_V_TDATA() {
    prediction_V_V_TDATA = grp_soft_max_fu_252_pred_V_V_TDATA.read();
}

void dense_layer::thread_prediction_V_V_TVALID() {
    prediction_V_V_TVALID = grp_soft_max_fu_252_pred_V_V_TVALID.read();
}

void dense_layer::thread_select_ln935_fu_656_p3() {
    select_ln935_fu_656_p3 = (!icmp_ln935_reg_1013.read()[0].is_01())? sc_lv<32>(): ((icmp_ln935_reg_1013.read()[0].to_bool())? ap_const_lv32_0: bitcast_ln739_fu_652_p1.read());
}

void dense_layer::thread_select_ln964_1_fu_615_p3() {
    select_ln964_1_fu_615_p3 = (!tmp_17_reg_1052.read()[0].is_01())? sc_lv<8>(): ((tmp_17_reg_1052.read()[0].to_bool())? ap_const_lv8_7F: ap_const_lv8_7E);
}

void dense_layer::thread_select_ln964_fu_890_p3() {
    select_ln964_fu_890_p3 = (!tmp_13_fu_882_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_13_fu_882_p3.read()[0].to_bool())? ap_const_lv8_7F: ap_const_lv8_7E);
}

void dense_layer::thread_sext_ln938_1_fu_402_p1() {
    sext_ln938_1_fu_402_p1 = esl_sext<30,25>(tmp_V_5_fu_396_p3.read());
}

void dense_layer::thread_sext_ln938_fu_676_p1() {
    sext_ln938_fu_676_p1 = esl_sext<15,9>(tmp_V_7_fu_669_p3.read());
}

void dense_layer::thread_shl_ln958_1_fu_850_p2() {
    shl_ln958_1_fu_850_p2 = (!sub_ln958_1_fu_845_p2.read().is_01())? sc_lv<32>(): m_1_fu_831_p1.read() << (unsigned short)sub_ln958_1_fu_845_p2.read().to_uint();
}

void dense_layer::thread_shl_ln958_fu_574_p2() {
    shl_ln958_fu_574_p2 = (!sub_ln958_fu_569_p2.read().is_01())? sc_lv<32>(): m_fu_549_p1.read() << (unsigned short)sub_ln958_fu_569_p2.read().to_uint();
}

void dense_layer::thread_sub_ln944_1_fu_710_p2() {
    sub_ln944_1_fu_710_p2 = (!ap_const_lv32_F.is_01() || !l_1_reg_1074.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_F) - sc_biguint<32>(l_1_reg_1074.read()));
}

void dense_layer::thread_sub_ln944_fu_432_p2() {
    sub_ln944_fu_432_p2 = (!ap_const_lv32_1E.is_01() || !l_fu_424_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1E) - sc_biguint<32>(l_fu_424_p3.read()));
}

void dense_layer::thread_sub_ln947_1_fu_471_p2() {
    sub_ln947_1_fu_471_p2 = (!ap_const_lv5_17.is_01() || !trunc_ln947_1_reg_1037.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_17) - sc_biguint<5>(trunc_ln947_1_reg_1037.read()));
}

void dense_layer::thread_sub_ln947_fu_745_p2() {
    sub_ln947_fu_745_p2 = (!ap_const_lv4_8.is_01() || !trunc_ln947_fu_741_p1.read().is_01())? sc_lv<4>(): (sc_bigint<4>(ap_const_lv4_8) - sc_biguint<4>(trunc_ln947_fu_741_p1.read()));
}

void dense_layer::thread_sub_ln958_1_fu_845_p2() {
    sub_ln958_1_fu_845_p2 = (!ap_const_lv32_19.is_01() || !sub_ln944_1_reg_1084.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_19) - sc_biguint<32>(sub_ln944_1_reg_1084.read()));
}

void dense_layer::thread_sub_ln958_fu_569_p2() {
    sub_ln958_fu_569_p2 = (!ap_const_lv32_19.is_01() || !sub_ln944_reg_1025.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_19) - sc_biguint<32>(sub_ln944_reg_1025.read()));
}

void dense_layer::thread_sub_ln964_1_fu_622_p2() {
    sub_ln964_1_fu_622_p2 = (!ap_const_lv8_C.is_01() || !trunc_ln943_1_reg_1042.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_C) - sc_biguint<8>(trunc_ln943_1_reg_1042.read()));
}

void dense_layer::thread_sub_ln964_fu_898_p2() {
    sub_ln964_fu_898_p2 = (!ap_const_lv8_6.is_01() || !trunc_ln943_reg_1079.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_6) - sc_biguint<8>(trunc_ln943_reg_1079.read()));
}

void dense_layer::thread_tmp_11_fu_725_p4() {
    tmp_11_fu_725_p4 = lsb_index_1_fu_719_p2.read().range(31, 1);
}

void dense_layer::thread_tmp_12_fu_778_p3() {
    tmp_12_fu_778_p3 = lsb_index_1_fu_719_p2.read().range(31, 31);
}

void dense_layer::thread_tmp_13_fu_882_p3() {
    tmp_13_fu_882_p3 = m_3_fu_863_p2.read().range(25, 25);
}

void dense_layer::thread_tmp_15_fu_455_p4() {
    tmp_15_fu_455_p4 = lsb_index_fu_450_p2.read().range(31, 1);
}

void dense_layer::thread_tmp_16_fu_503_p3() {
    tmp_16_fu_503_p3 = lsb_index_fu_450_p2.read().range(31, 31);
}

void dense_layer::thread_tmp_4_fu_909_p3() {
    tmp_4_fu_909_p3 = esl_concat<1,8>(p_Result_16_reg_994.read(), add_ln964_fu_903_p2.read());
}

void dense_layer::thread_tmp_5_fu_633_p3() {
    tmp_5_fu_633_p3 = esl_concat<1,8>(p_Result_13_reg_1007.read(), add_ln964_1_fu_627_p2.read());
}

void dense_layer::thread_tmp_9_fu_322_p3() {
    tmp_9_fu_322_p3 = esl_concat<8,3>(f_0_reg_241.read(), ap_const_lv3_0);
}

void dense_layer::thread_tmp_V_3_fu_391_p2() {
    tmp_V_3_fu_391_p2 = (!ap_const_lv25_0.is_01() || !mul_ln941_reg_1000.read().is_01())? sc_lv<25>(): (sc_biguint<25>(ap_const_lv25_0) - sc_bigint<25>(mul_ln941_reg_1000.read()));
}

void dense_layer::thread_tmp_V_5_fu_396_p3() {
    tmp_V_5_fu_396_p3 = (!p_Result_13_reg_1007.read()[0].is_01())? sc_lv<25>(): ((p_Result_13_reg_1007.read()[0].to_bool())? tmp_V_3_fu_391_p2.read(): mul_ln941_reg_1000.read());
}

void dense_layer::thread_tmp_V_7_fu_669_p3() {
    tmp_V_7_fu_669_p3 = (!p_Result_16_reg_994.read()[0].is_01())? sc_lv<9>(): ((p_Result_16_reg_994.read()[0].to_bool())? tmp_V_fu_663_p2.read(): dense_biases_V_q0.read());
}

void dense_layer::thread_tmp_V_fu_663_p2() {
    tmp_V_fu_663_p2 = (!ap_const_lv9_0.is_01() || !dense_biases_V_q0.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_biguint<9>(dense_biases_V_q0.read()));
}

void dense_layer::thread_tmp_s_fu_334_p3() {
    tmp_s_fu_334_p3 = esl_concat<8,1>(f_0_reg_241.read(), ap_const_lv1_0);
}

void dense_layer::thread_trunc_ln943_1_fu_446_p1() {
    trunc_ln943_1_fu_446_p1 = l_fu_424_p3.read().range(8-1, 0);
}

void dense_layer::thread_trunc_ln943_fu_706_p1() {
    trunc_ln943_fu_706_p1 = l_1_fu_698_p3.read().range(8-1, 0);
}

void dense_layer::thread_trunc_ln944_1_fu_438_p1() {
    trunc_ln944_1_fu_438_p1 = sub_ln944_fu_432_p2.read().range(30-1, 0);
}

void dense_layer::thread_trunc_ln944_fu_715_p1() {
    trunc_ln944_fu_715_p1 = sub_ln944_1_fu_710_p2.read().range(15-1, 0);
}

void dense_layer::thread_trunc_ln947_1_fu_442_p1() {
    trunc_ln947_1_fu_442_p1 = sub_ln944_fu_432_p2.read().range(5-1, 0);
}

void dense_layer::thread_trunc_ln947_fu_741_p1() {
    trunc_ln947_fu_741_p1 = sub_ln944_1_fu_710_p2.read().range(4-1, 0);
}

void dense_layer::thread_xor_ln949_1_fu_511_p2() {
    xor_ln949_1_fu_511_p2 = (tmp_16_fu_503_p3.read() ^ ap_const_lv1_1);
}

void dense_layer::thread_xor_ln949_fu_786_p2() {
    xor_ln949_fu_786_p2 = (tmp_12_fu_778_p3.read() ^ ap_const_lv1_1);
}

void dense_layer::thread_zext_ln1116_1_fu_342_p1() {
    zext_ln1116_1_fu_342_p1 = esl_zext<12,9>(tmp_s_fu_334_p3.read());
}

void dense_layer::thread_zext_ln1116_2_fu_357_p1() {
    zext_ln1116_2_fu_357_p1 = esl_zext<64,12>(add_ln1116_1_fu_352_p2.read());
}

void dense_layer::thread_zext_ln1116_fu_330_p1() {
    zext_ln1116_fu_330_p1 = esl_zext<12,11>(tmp_9_fu_322_p3.read());
}

void dense_layer::thread_zext_ln13_fu_270_p1() {
    zext_ln13_fu_270_p1 = esl_zext<64,4>(phi_ln13_reg_207.read());
}

void dense_layer::thread_zext_ln15_fu_281_p1() {
    zext_ln15_fu_281_p1 = esl_zext<10,4>(d_0_reg_218.read());
}

void dense_layer::thread_zext_ln19_fu_301_p1() {
    zext_ln19_fu_301_p1 = esl_zext<12,4>(d_0_reg_218.read());
}

void dense_layer::thread_zext_ln21_fu_317_p1() {
    zext_ln21_fu_317_p1 = esl_zext<64,8>(f_0_reg_241.read());
}

void dense_layer::thread_zext_ln936_fu_297_p1() {
    zext_ln936_fu_297_p1 = esl_zext<64,4>(d_0_reg_218.read());
}

void dense_layer::thread_zext_ln947_1_fu_476_p1() {
    zext_ln947_1_fu_476_p1 = esl_zext<30,5>(sub_ln947_1_fu_471_p2.read());
}

void dense_layer::thread_zext_ln947_fu_751_p1() {
    zext_ln947_fu_751_p1 = esl_zext<15,4>(sub_ln947_fu_745_p2.read());
}

void dense_layer::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln13_fu_275_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln15_fu_285_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln19_fu_305_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 1048576 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && esl_seteq<1,1,1>(grp_soft_max_fu_252_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state21;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

