// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _normalization_HH_
#define _normalization_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "cnn_fpext_32ns_64bkb.h"
#include "cnn_ddiv_64ns_64ncud.h"

namespace ap_rtl {

struct normalization : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > img_in_V_dout;
    sc_in< sc_logic > img_in_V_empty_n;
    sc_out< sc_logic > img_in_V_read;
    sc_out< sc_lv<14> > img_out_V_V_din;
    sc_in< sc_logic > img_out_V_V_full_n;
    sc_out< sc_logic > img_out_V_V_write;
    sc_signal< sc_logic > ap_var_for_const1;
    sc_signal< sc_lv<64> > ap_var_for_const0;


    // Module declarations
    normalization(sc_module_name name);
    SC_HAS_PROCESS(normalization);

    ~normalization();

    sc_trace_file* mVcdFile;

    cnn_fpext_32ns_64bkb<1,2,32,64>* cnn_fpext_32ns_64bkb_U11;
    cnn_ddiv_64ns_64ncud<1,22,64,64,64>* cnn_ddiv_64ns_64ncud_U12;
    sc_signal< sc_lv<28> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > img_in_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln19_fu_120_p2;
    sc_signal< sc_logic > img_out_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state28;
    sc_signal< sc_lv<5> > r_fu_114_p2;
    sc_signal< sc_lv<5> > r_reg_408;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<5> > c_fu_126_p2;
    sc_signal< sc_lv<5> > c_reg_416;
    sc_signal< bool > ap_block_state3;
    sc_signal< sc_lv<64> > grp_fu_99_p1;
    sc_signal< sc_lv<64> > tmp_5_reg_426;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<64> > grp_fu_103_p2;
    sc_signal< sc_lv<64> > v_assign_reg_431;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_lv<54> > man_V_4_fu_183_p3;
    sc_signal< sc_lv<54> > man_V_4_reg_436;
    sc_signal< sc_logic > ap_CS_fsm_state27;
    sc_signal< sc_lv<12> > sh_amt_fu_221_p3;
    sc_signal< sc_lv<12> > sh_amt_reg_441;
    sc_signal< sc_lv<14> > trunc_ln583_fu_235_p1;
    sc_signal< sc_lv<14> > trunc_ln583_reg_446;
    sc_signal< sc_lv<1> > and_ln603_fu_327_p2;
    sc_signal< sc_lv<1> > and_ln603_reg_451;
    sc_signal< sc_lv<1> > or_ln603_fu_333_p2;
    sc_signal< sc_lv<1> > or_ln603_reg_456;
    sc_signal< sc_lv<14> > select_ln603_4_fu_339_p3;
    sc_signal< sc_lv<14> > select_ln603_4_reg_461;
    sc_signal< sc_lv<1> > or_ln603_4_fu_353_p2;
    sc_signal< sc_lv<1> > or_ln603_4_reg_466;
    sc_signal< sc_lv<5> > r_0_reg_77;
    sc_signal< sc_lv<5> > c_0_reg_88;
    sc_signal< sc_lv<1> > icmp_ln18_fu_108_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > ireg_V_fu_132_p1;
    sc_signal< sc_lv<11> > exp_tmp_V_fu_147_p4;
    sc_signal< sc_lv<52> > trunc_ln565_fu_161_p1;
    sc_signal< sc_lv<53> > tmp_2_fu_165_p3;
    sc_signal< sc_lv<54> > p_Result_2_fu_173_p1;
    sc_signal< sc_lv<1> > p_Result_s_fu_139_p3;
    sc_signal< sc_lv<54> > man_V_3_fu_177_p2;
    sc_signal< sc_lv<63> > trunc_ln556_fu_135_p1;
    sc_signal< sc_lv<12> > zext_ln461_fu_157_p1;
    sc_signal< sc_lv<12> > F2_fu_197_p2;
    sc_signal< sc_lv<1> > icmp_ln581_fu_203_p2;
    sc_signal< sc_lv<12> > add_ln581_fu_209_p2;
    sc_signal< sc_lv<12> > sub_ln581_fu_215_p2;
    sc_signal< sc_lv<1> > tmp_7_fu_251_p3;
    sc_signal< sc_lv<1> > icmp_ln571_fu_191_p2;
    sc_signal< sc_lv<1> > icmp_ln582_fu_229_p2;
    sc_signal< sc_lv<1> > xor_ln571_fu_267_p2;
    sc_signal< sc_lv<1> > or_ln582_fu_279_p2;
    sc_signal< sc_lv<1> > xor_ln582_fu_285_p2;
    sc_signal< sc_lv<1> > icmp_ln585_fu_239_p2;
    sc_signal< sc_lv<1> > and_ln581_fu_291_p2;
    sc_signal< sc_lv<1> > xor_ln585_fu_297_p2;
    sc_signal< sc_lv<1> > or_ln581_fu_315_p2;
    sc_signal< sc_lv<1> > icmp_ln603_fu_245_p2;
    sc_signal< sc_lv<1> > xor_ln581_fu_321_p2;
    sc_signal< sc_lv<1> > and_ln585_2_fu_309_p2;
    sc_signal< sc_lv<1> > and_ln585_fu_303_p2;
    sc_signal< sc_lv<14> > select_ln588_fu_259_p3;
    sc_signal< sc_lv<1> > and_ln582_fu_273_p2;
    sc_signal< sc_lv<1> > or_ln603_3_fu_347_p2;
    sc_signal< sc_lv<32> > sext_ln581_fu_359_p1;
    sc_signal< sc_lv<54> > zext_ln586_fu_362_p1;
    sc_signal< sc_lv<54> > ashr_ln586_fu_366_p2;
    sc_signal< sc_lv<14> > sext_ln581cast_fu_375_p1;
    sc_signal< sc_lv<14> > shl_ln604_fu_379_p2;
    sc_signal< sc_lv<14> > trunc_ln586_fu_371_p1;
    sc_signal< sc_lv<14> > select_ln603_fu_384_p3;
    sc_signal< sc_lv<14> > select_ln603_5_fu_391_p3;
    sc_signal< sc_logic > grp_fu_99_ce;
    sc_signal< sc_lv<28> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<28> ap_ST_fsm_state1;
    static const sc_lv<28> ap_ST_fsm_state2;
    static const sc_lv<28> ap_ST_fsm_state3;
    static const sc_lv<28> ap_ST_fsm_state4;
    static const sc_lv<28> ap_ST_fsm_state5;
    static const sc_lv<28> ap_ST_fsm_state6;
    static const sc_lv<28> ap_ST_fsm_state7;
    static const sc_lv<28> ap_ST_fsm_state8;
    static const sc_lv<28> ap_ST_fsm_state9;
    static const sc_lv<28> ap_ST_fsm_state10;
    static const sc_lv<28> ap_ST_fsm_state11;
    static const sc_lv<28> ap_ST_fsm_state12;
    static const sc_lv<28> ap_ST_fsm_state13;
    static const sc_lv<28> ap_ST_fsm_state14;
    static const sc_lv<28> ap_ST_fsm_state15;
    static const sc_lv<28> ap_ST_fsm_state16;
    static const sc_lv<28> ap_ST_fsm_state17;
    static const sc_lv<28> ap_ST_fsm_state18;
    static const sc_lv<28> ap_ST_fsm_state19;
    static const sc_lv<28> ap_ST_fsm_state20;
    static const sc_lv<28> ap_ST_fsm_state21;
    static const sc_lv<28> ap_ST_fsm_state22;
    static const sc_lv<28> ap_ST_fsm_state23;
    static const sc_lv<28> ap_ST_fsm_state24;
    static const sc_lv<28> ap_ST_fsm_state25;
    static const sc_lv<28> ap_ST_fsm_state26;
    static const sc_lv<28> ap_ST_fsm_state27;
    static const sc_lv<28> ap_ST_fsm_state28;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<64> ap_const_lv64_406FE00000000000;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<5> ap_const_lv5_1C;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<54> ap_const_lv54_0;
    static const sc_lv<63> ap_const_lv63_0;
    static const sc_lv<12> ap_const_lv12_433;
    static const sc_lv<12> ap_const_lv12_8;
    static const sc_lv<12> ap_const_lv12_FF8;
    static const sc_lv<12> ap_const_lv12_36;
    static const sc_lv<12> ap_const_lv12_E;
    static const sc_lv<14> ap_const_lv14_3FFF;
    static const sc_lv<14> ap_const_lv14_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_F2_fu_197_p2();
    void thread_add_ln581_fu_209_p2();
    void thread_and_ln581_fu_291_p2();
    void thread_and_ln582_fu_273_p2();
    void thread_and_ln585_2_fu_309_p2();
    void thread_and_ln585_fu_303_p2();
    void thread_and_ln603_fu_327_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state27();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_state3();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ashr_ln586_fu_366_p2();
    void thread_c_fu_126_p2();
    void thread_exp_tmp_V_fu_147_p4();
    void thread_grp_fu_99_ce();
    void thread_icmp_ln18_fu_108_p2();
    void thread_icmp_ln19_fu_120_p2();
    void thread_icmp_ln571_fu_191_p2();
    void thread_icmp_ln581_fu_203_p2();
    void thread_icmp_ln582_fu_229_p2();
    void thread_icmp_ln585_fu_239_p2();
    void thread_icmp_ln603_fu_245_p2();
    void thread_img_in_V_blk_n();
    void thread_img_in_V_read();
    void thread_img_out_V_V_blk_n();
    void thread_img_out_V_V_din();
    void thread_img_out_V_V_write();
    void thread_ireg_V_fu_132_p1();
    void thread_man_V_3_fu_177_p2();
    void thread_man_V_4_fu_183_p3();
    void thread_or_ln581_fu_315_p2();
    void thread_or_ln582_fu_279_p2();
    void thread_or_ln603_3_fu_347_p2();
    void thread_or_ln603_4_fu_353_p2();
    void thread_or_ln603_fu_333_p2();
    void thread_p_Result_2_fu_173_p1();
    void thread_p_Result_s_fu_139_p3();
    void thread_r_fu_114_p2();
    void thread_select_ln588_fu_259_p3();
    void thread_select_ln603_4_fu_339_p3();
    void thread_select_ln603_5_fu_391_p3();
    void thread_select_ln603_fu_384_p3();
    void thread_sext_ln581_fu_359_p1();
    void thread_sext_ln581cast_fu_375_p1();
    void thread_sh_amt_fu_221_p3();
    void thread_shl_ln604_fu_379_p2();
    void thread_sub_ln581_fu_215_p2();
    void thread_tmp_2_fu_165_p3();
    void thread_tmp_7_fu_251_p3();
    void thread_trunc_ln556_fu_135_p1();
    void thread_trunc_ln565_fu_161_p1();
    void thread_trunc_ln583_fu_235_p1();
    void thread_trunc_ln586_fu_371_p1();
    void thread_xor_ln571_fu_267_p2();
    void thread_xor_ln581_fu_321_p2();
    void thread_xor_ln582_fu_285_p2();
    void thread_xor_ln585_fu_297_p2();
    void thread_zext_ln461_fu_157_p1();
    void thread_zext_ln586_fu_362_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
